name: Testes da Página HTML

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v2

    - name: Configurar Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Instalar dependências
      run: npm install

    - name: Iniciar Live Server
      run: |
        npx live-server --port=5500 --no-browser --quiet &   # Inicia o Live Server em segundo plano
        sleep 5  # Aguarda alguns segundos para garantir que o Live Server tenha sido iniciado corretamente

    - name: Executar testes
      run: npm test

    - name: Encerrar Live Server
      run: kill $(lsof -t -i:5500) || true   # Encerra o Live Server após a conclusão dos testes
